# In this class, you will learn to use Python!
Helpful online reference for Python 
  * https://docs.python.org/3/tutorial/introduction.html
  * https://docs.python.org/3/tutorial/controlflow.html
  
Optional extra learning material: An online course for Python 
  * https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016/index.htm

# Code cells
Directly below is a code cell. Click on the cell to make it active. Press `Shift` + `Return` to execute all of the code in an active cell.

In [2]:
print('Hello world')

Hello world


# Markdown cells
This cell does not contain code. It can be used to keep notes, or to make a readable document that you can share with others. What happens when you press `Shift` + `Return`? More information on markdown cells is in the notebook `Typesetting Equations.ipynb`.

# Code Comments

In [3]:
# If you begin a line of code with a `#` symbol, Python will ignore it. 
# These allow you to keep notes in your code.
# The Jupyter notebook automatically formats them with a different color and font so that they stand out.
# What happens when you execute this cell? (hint: nothing)

# Notebook header
This cell needs to be at the top of every notebook. It loads useful tools for math and plotting. **Always execute this cell before running any code in a notebook!**

In [4]:
#### These three lines should be in a cell at the top of any notebook
#### These lines load standard tools that will be usefull to us
#### Always execute this cell before running any code in a notebook
%pylab inline
%config InlineBackend.figure_format = 'retina'
from ipywidgets import interact

Populating the interactive namespace from numpy and matplotlib


# Understanding cell output
Use the `print()` function to output raw values stored in a variable

In [5]:
print('hello world')
print(10000000000)
x = 10
y = 1.1321
print(x, y)
n = arange(3)
print(n)

hello world
10000000000
10 1.1321
[0 1 2]


# How to get help within Jupyter

In [6]:
### Try uncommenting (delete the `#` symbol at the beginning of the line) any of these
help(arange)
#help(plot)
#help(zeros)
#help(linspace)

### You can also use `?` instead of `help()`
### Try uncommenting and running one of the following lines
#?plot
#?zeros
#?linspace

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : number, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : number
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off affects the length of `out`.
   

# Lesson 1
Every time you execute a cell (shift + return), the variables are saved into the workspace. If you push the reset button (circle with the arrow at the top or the 'Kernel' tab -> restart) the workspace is cleared. **Remember: after restarting, you will have to run the top cell that loads the common modules.** If you don't you will likely get an error. 

If you run a cell that depends on variables that were generated in a previous cell, then you might get an error if you execute them out of order.

In [7]:
## Lesson 1, cell A
x = 2.2
print(x)

2.2


In [8]:
## Lesson 1, cell B
y = x*5
print(y)

11.0


### Try restarting the notebook
  * Restart the notebook (circle with the arrow at the top or the 'Kernel' tab -> restart)
  * Execute Lesson 1, cell B. If you restarted the notebook successfully, you should get an error.
  * Now execute Lesson 1, cell A first. Do you get an error? Now do you get an error if you execute Execute 1, cell B?

Variables in Python store numeric values or other data structures (like arrays which we will see in Lesson 2). This means code can contain statements that are logically absurd if interpreted as mathematical equations (like `x = x + 3`). You should read `x = 5` as, "store the value `5` in the variable called `x`."

In [9]:
x = 5
print(x)
x = x + 3 # store the value obtained from the operation of `x+3` (which is 5 + 3 = 8) in the variable x
print(x)

5
8


### Some math
Most mathematical operations work as expected. For example
  * $xy$ = `x*y`
  * $x/y$ = `x/y`
  * $\ln(x)$ = `log(x)`
  * $e^x$ = `exp(x)`
  * $\cos(x)$ = `cos(x)`

But some work differently. In Python, the exponentiation operator is `**` instead of `^`.
  * $x^2$ = `x**2`

In [10]:
x = 5.5
print('x^2 =', x**2)

x^2 = 30.25


### What happens if you try `x^2` instead of `x**2`?

In [11]:
x = 1.5
y = x^2
print('x^2 =', y)

TypeError: unsupported operand type(s) for ^: 'float' and 'int'

# Lesson 2: Arrays
Arrays are similar to mathematical vectors. Typically, it is a collection of numbers that can be accessed by an integer index. For example $x = [20, 4, 7]$ is an array with $x[0] = 20$, $x[1] = 4$, and $x[2] = 7$.

Accessing array elements is done using square brackets. If $j=0,1,2,\ldots$ is a nonnegative integer and $x$ is an array then $x[j]$ is the value stored in the array. Note that Python arrays start their index from zero.

There are two types of arrays that are useful for us. Examples of each are included in the following cells.
  1. **Lists:** A list is very simple and adaptable. You don't need to know how large a list will be (i.e., how  many elements it will have) before you create one. However, you cannot do mathematical operations on a list
  2. **Numpy array:** You must know how many elements this type of array will have when you create it. The benefit is that you can do mathematical operations to it. By default mathematical operations are applied to each element individually.

In [12]:
### Lists
a_list = [6, 22, 4]
print(a_list)
another_list = [9, -5.1, 0]
print(another_list)

[6, 22, 4]
[9, -5.1, 0]


In [13]:
# this will generate an error because multiplication is not defined for lists
a_list*another_list

TypeError: can't multiply sequence by non-int of type 'list'

In [14]:
a_npArray = array([6, 22, 4])
print(a_npArray)
another_npArray = array([9, -5.1, 0])
print(another_npArray)
y = a_npArray*another_npArray
print(y)

[ 6 22  4]
[ 9.  -5.1  0. ]
[  54.  -112.2    0. ]


In [15]:
print('Transpose of an array')
print(a_npArray.T)
print('elementwise is the default for Numpy arrays')
print(a_npArray*a_npArray.T)
print('matrix multiplication')
print(a_npArray@a_npArray.T)

Transpose of an array
[ 6 22  4]
elementwise is the default for Numpy arrays
[ 36 484  16]
matrix multiplication
[ 6 22  4]


In [16]:
square_array = array([[0, 1], [1, 0]]) ## the construction is just a list of lists!
print(square_array)
print('elementwise multiplication')
print(square_array*square_array)
print('matrix multiplication')
print(square_array@square_array)
print('indexing into a higher dimensional array is done with multiple integer indices')
print(square_array[0, 1])
print(square_array[1, 1])

[[0 1]
 [1 0]]
elementwise multiplication
[[0 1]
 [1 0]]
matrix multiplication
[[1 0]
 [0 1]]
indexing into a higher dimensional array is done with multiple integer indices
1
0


### You can easily convert between lists, arrays, and matrices as needed

In [31]:
x = [1, 4, 3]
y = array(x) # convert from a list to an array
v = list(y) # convert from an array to a list

### Shortcut for accessing the end of an array
Sometimes you need to access the last element of an array, you can do this by using a negative integer index, which counts from the end backward

In [18]:
x = array([1, 4, 3])
print(x[2]) ## the last element
print(x[-1]) ## also the last element 
print(x[-2]) ## the second to last element

3
3
4


### Array construction and assignment

In [19]:
## To make an array filled with zeros
x = zeros(10) # A 10-element array filled with zeros
y = ones(7) # A 7-element array filled with ones

## Set one value in an array to a specified value
x[1] = 66
print(x)
y[0] = -5
print(y)

[ 0. 66.  0.  0.  0.  0.  0.  0.  0.  0.]
[-5.  1.  1.  1.  1.  1.  1.]


## We have much more to say about arrays–namely advance features like slicing, fancy indexing, and broadcasting–but these will wait for another lesson

# Lesson 3: for loops
In this class, the 'for loop' will play an important role. A loop is a way of repeating a proceedure a certain number of times. For loops are initiated with the word `for`, followed by the choice of a loop variable and the values the loop variable will take during each iteration. To specify the range of values, the most common approach is to use the function `arange()` which creates an array of integers. 

The body of the loop is the code that gets repeated. It is specified by indenting each line (the first line that defines the loop is not indented). The body of the loop ends on the first line that is unindented. 

Several examples are included below.

In [20]:
for n in arange(13):
    print('hello world')
print('Loop finished now')

hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
Loop finished now


In [21]:
for j in arange(5):
    print(j)

0
1
2
3
4


In [22]:
for q in arange(3):
    print(q**2)

0
1
4


In [23]:
for m in arange(3, 8):
    print(m)

3
4
5
6
7


In [24]:
a_list = [] # an empty list that we will fill up with values
t = linspace(0, 11, 4) # creates an array of (4) evenly spaced points between 0 and 11
for j in arange(4):
    y = sin(t[j])
    a_list.append(y) # inserts the value of y to the end of the list
    print(a_list)
print('Loop is finished')
an_array = array(a_list)
print(an_array**2)

[0.0]
[0.0, -0.5012770485883448]
[0.0, -0.5012770485883448, 0.8674968696188059]
[0.0, -0.5012770485883448, 0.8674968696188059, -0.9999902065507035]
Loop is finished
[0.         0.25127868 0.75255082 0.99998041]


# Lesson 4: functions
Functions work much like mathematical functions: they take an input and return an output. Some examples are below.

In [25]:
def my_function(x):
    y = 2*x
    return y

print(my_function(2))
print(my_function(5))

4
10


In [26]:
def another_function(x, y, z):
    s1 = 2*x
    s2 = s1 + 5/y
    s3 = z*s2
    return s3

print(another_function(2, 1, 5))
print(another_function(16, 1, -1))

45.0
-37.0


### Note that function names cannot have spaces or special characters.

# Lesson 5: if statements
If statements are a useful tool for controlling the behavior of your program. 

In [27]:
x = 11 # try changing this value
if x < 5:
    print('x is less than 5')
elif x > 10: ## read `elif` as 'else if'
    print('x is greater than 10')
else:
    print('x is neither less than 5 nor greater than 10')

x is greater than 10


In [28]:
def fancy_function(x):
    if x < 5:
        return 'x is less than 5'
    elif x > 10:
        return 'x is greater than 10'
    else:
        return 'x is neither less than 5 nor greater than 10'
    
print(fancy_function(11))
print(fancy_function(8))
print(fancy_function(1))

x is greater than 10
x is neither less than 5 nor greater than 10
x is less than 5


In [29]:
## Tip: in Python, you can write compound conditionals
x = 2
print(0 < x < 10) ## True if x is greater than 0 and less than 10, otherwise False
x = -1
print(0 < x < 10)
print(0 < 5 <= 6)

True
False
True


### Check if a value is contained in an array

In [30]:
a = [0, -22, 3, 8, 2, 7]
x = 2
print(x in a)
x = 1
print(x in a)

True
False


# There is much more, and we will learn through examples throughout the semester!